### PR TITLE
Add 5 failing tests for the most difficult to render Unicode samples.

### PR DESCRIPTION
**Pull request by alfredleo**
**Fixes** #
There is no fix yet. 
#### Proposed Changes
* Just want to ask if you plan to have those kind of errors get fixed. 
* If yes I can try to find a solution and rework PR.
* https://github.com/alfredleo/SimpleSolutions Here I have tests with grapheme_substr. 

$ ./vendor/bin/phpunit                                                                                                     PHPUnit 7.5.6 by Sebastian Bergmann and contributors.                                                                                                                                                                                                 Runtime:       PHP 7.2.14                                                                                                  Configuration: C:\Work\libraries\portable-utf8\phpunit.xml                                                                 Error:         No code coverage driver is available                                                                                                                                                                                                   .............................................................   61 / 1792 (  3%)                                           .............................................................  122 / 1792 (  6%)                                           .............................................................  183 / 1792 ( 10%)                                           ......F......................................................  244 / 1792 ( 13%)                                           .............................................................  305 / 1792 ( 17%)                                           .............................................................  366 / 1792 ( 20%)                                           .............................................................  427 / 1792 ( 23%)                                           .............................................................  488 / 1792 ( 27%)                                           .............................................................  549 / 1792 ( 30%)                                           .............................................................  610 / 1792 ( 34%)                                           .............................................................  671 / 1792 ( 37%)                                           .............................................................  732 / 1792 ( 40%)                                           .............................................................  793 / 1792 ( 44%)                                           .............................................................  854 / 1792 ( 47%)                                           .............................................................  915 / 1792 ( 51%)                                           .............................................................  976 / 1792 ( 54%)                                           ............................................................. 1037 / 1792 ( 57%)                                           ............................................................. 1098 / 1792 ( 61%)                                           ............................................................. 1159 / 1792 ( 64%)                                           ............................................................. 1220 / 1792 ( 68%)                                           ............................................................. 1281 / 1792 ( 71%)                                           ............................................................. 1342 / 1792 ( 74%)                                           ............................................................. 1403 / 1792 ( 78%)                                           ............................................................. 1464 / 1792 ( 81%)                                           ............................................................. 1525 / 1792 ( 85%)                                           ............................................................. 1586 / 1792 ( 88%)                                           ............................................................. 1647 / 1792 ( 91%)                                           ............................................................. 1708 / 1792 ( 95%)                                           ............................................................. 1769 / 1792 ( 98%)                                           .......................                                       1792 / 1792 (100%)                                                                                                                                                                      Time: 6.65 seconds, Memory: 66.00 MB                                                                                                                                                                                                                  There was 1 failure:                                                                                                                                                                                                                                  1) voku\tests\Utf8GlobalNonStrictPart2Test::testStrrev                                                                     error by 👱👱🏻👱🏼👱🏽👱🏾👱🏿                                                                                            Failed asserting that two strings are identical.                                                                           --- Expected                                                                                                               +++ Actual                                                                                                                 @@ @@                                                                                                                      -'👱🏿👱🏾👱🏽👱🏼👱🏻👱'                                                                                                  +'🏿👱🏾👱🏽👱🏼👱🏻👱👱'
--

<!-- Reviewable:start -->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/voku/portable-utf8/81)
<!-- Reviewable:end -->

### CODE REVIEW

**Comment by voku** [comment]
Hi, thanks for the test cases ... 

... why do you think that this is correct?

'👱👱🏻👱🏼👱🏽👱🏾👱🏿' => '👱🏿👱🏾👱🏽👱🏼👱🏻👱'

I get this from the "UTF8::strrev() method.

'👱👱🏻👱🏼👱🏽👱🏾👱🏿' => '🏿👱🏾👱🏽👱🏼👱🏻👱👱',

**Comment by alfredleo** [comment]
I am thinking on how to implement a fix for this.

 The only working solution so far is using grapheme_* functions in php:
```php
function reverse($string)
{
    $length = grapheme_strlen($string);
    $ret = [];
    for ($i = 0; $i < $length; $i += 1) {
        $ret[] = grapheme_substr($string, $i, 1);
    }
    return implode(array_reverse($ret));
}
```
It is hard to implement this by hand. We can make a check on this method. If it exists we use it. Otherwise we fall back to old implementation. What do you think about it?

**Comment by voku** [comment]
What do you think of this "hack"? -> https://github.com/voku/portable-utf8/commit/5e3b5eebbe4fe2f92622fdb94d04ad9b97b88ec5#diff-890805f35966ea20340b9076d7b47329R9194

We encode the emoji chars, so that we can revert the string and then we can decode it + use "grapheme" if possible.

**Comment by alfredleo** [comment]
That actually fix the problem. Thanks. As a further development, one could develop portable grapheme aware functions, to make this library really 'portable'. But that like a redesign of a wheel. So thank you, good job.

**Comment by alfredleo** [comment]
Tested candidates for a working grapheme polyfill: `symfony/polyfill-intl-grapheme` and `patchwork/utf8`. Both failed with the last 3 tests. So only working solution for all corner cases is `intl` PHP extension.

**Pull request merged**
