### PR TITLE
Simplify and update phpstan configuration

### PR DESCRIPTION
**Pull request by szepeviktor**
Makes PHPStan return "OK"

---
This change is [Reviewable](https://reviewable.io/reviews/voku/portable-utf8/99)

### CODE REVIEW

**Comment by szepeviktor** [comment]
On PHP 7.3 with `PHP_COMPOSER_SETUP=lowest PHP_EXTENSION=false` PHPStan complains.

```
 ------ -------------------------------------------------------------------- 

  Line   voku/helper/UTF8.php                                                

 ------ -------------------------------------------------------------------- 

  8313   Function mb_str_split not found.                                    

 ------ -------------------------------------------------------------------- 
```

How could it be?

**Comment by szepeviktor** [comment]
Could it be this change?

> - use "mb_str_split" with PHP >= 7.4 + mbstring support (performance++)

**Comment by voku** [comment]
@szepeviktor Thanks for the clean-up and I think phpstan did not understand the ```if (Bootup::is_php('7.4')) {``` check.

**Comment by szepeviktor** [comment]
I think `if (Bootup::is_php('7.4')) {` is not executed on PHP 7.3.
That is why `mb_str_split()` is not available.

**Comment by szepeviktor** [comment]
...I see!

If we teach `is_php()` to PHPStan it may cease to complain.

**Comment by szepeviktor** [comment]
@voku Please see the conversion on this matter: https://github.com/phpstan/phpstan/issues/3576#issuecomment-654772559

What do you think about `function_exists()` instead of `Bootup::is_php()` ?

**Comment by voku** [comment]
```function_exists``` should work and we can also cache the result, so that we do not check this every time.

**Comment by szepeviktor** [comment]
1M `function_exists` call takes 0.064774036407471 seconds on my slow server.

```php
<?php

$start = microtime(true);
for ($run = 0; $run < 1e6; $run += 1) {
    $exists = function_exists('mb_str_split');
}
echo microtime(true) - $start, "\n";
```

So 1 call takes 64 nanosec :)

**Comment by voku** [comment]
@szepeviktor I added the "function_exists" check but phpstan still complains about "Function mb_str_split not found." :/ I think I did something wrong, because I can't see it on my local system?

**Comment by szepeviktor** [comment]
> I think I did something wrong because I can't see it on my local system?

No! That is fine.
The above linked PHPStan issue is a **feature request**.

Currently the only solution is to define the function for PHPStan only.

```yaml
parameters:
    scanFiles:
        - tests/phpstan/functions.php
```

**Comment by szepeviktor** [comment]
> I can't see it on my local system?

Maybe your PHP version is not 7.3 ...

**Pull request merged**
